x-author: Riikka Jääskä
x-date: 2025-10

openapi: 3.0.0
info:
  title: Process Status Interface Standard for Public Service Transactions
  version: "0.1"
  description: >
    An interface specification for transmitting status information from public sector digital services
    to a unified citizen-facing view.

paths:
  /status-update:
    post:
      summary: Submit a status update for a public service process
      operationId: submitStatusUpdate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdate'
      responses:
        '202':
          description: Accepted – status update queued/processed
        '400':
          description: Bad request – validation error
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error

components:
  schemas:
    StatusUpdate:
      type: object
      required:
        - authority_id
        - authority_name
        - service_id
        - service_name
        - case_id
        - user_id
        - status_type
		- process_type
        - response_type
		- expected_action
        - timestamp
        - source_system
      properties:
        authority_id:
          type: string
          description: National identifier of the authority
        authority_name:
          type: string
          description: Descriptive authority name
        service_id:
          type: string
          description: Identifier from a national service catalogue
        service_name:
          type: string
          description: Descriptive service name
        case_id:
          type: string
          description: Unique case identifier from the source system
        user_id:
          type: string
          description: Person ID or organizational ID
        status_type:
          type: string
          description: Standardized status label
          enum:
            - draft
            - received_by_authority
            - in_progress
            - response_required
            - resolved_by_authority
            - closed_by_user
            - reminder
        status_detail:
          type: string
          description: Optional authority-specific detail
        process_type:
          type: string
          enum: 
            - application_process
            - notification_process
            - inspection_process
            - event_triggered_process
            - periodic_review_process
            - passive_update_process
        response_type:
          type: string
          enum: [mandatory, optional, informational]
        expected_action:
          type: string
        deadline:
          type: string
          format: date
          description: Deadline date if applicable (YYYY-MM-DD)
        consequence_if_no_action:
          type: string
        notification_channels:
          type: array
          items:
            type: string
            enum:
              - official_messaging_portal
              - online_service_ui
              - paper_mail
              - messaging_portal
              - email
              - sms
              - phone_call
        response_channels:
          type: array
          items:
            type: string
            enum:
              - official_messaging_portal
              - online_service_ui
              - paper_mail
              - messaging_portal
              - email
              - sms
              - phone_call
        notification_id:
          type: string
        appeal_available:
          type: boolean
        timestamp:
          type: string
          format: date-time
        source_system:
          type: string


